export const FETCH_CATEGORIES_STARTED = 'FETCH_CATEGORIES_STARTED';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_ENDED = 'FETCH_CATEGORIES_ENDED';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';
