export const FETCH_CATEGORIES_STARTED = 'FETCH_CATEGORIES_STARTED';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_ENDED = 'FETCH_CATEGORIES_ENDED';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';

export const FETCH_ITEMS_STARTED = 'FETCH_ITEMS_STARTED';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_ENDED = 'FETCH_ITEMS_ENDED';
export const FETCH_ITEMS_FAILED = 'FETCH_ITEMS_FAILED';
